after 'development:clans', :roles do
  User.create({:name => 'George Washington', :email => 'email_1', :uid => 'uid_1', :role_id => 1, :clan_id => 1})
  User.create({:name => 'John Adams', :email => 'email_2', :uid => 'uid_2', :role_id => 1, :clan_id => 1})
  User.create({:name => 'Thomas Jefferson', :email => 'email_3', :uid => 'uid_3', :role_id => 1, :clan_id => 2})
  User.create({:name => 'James Madison', :email => 'email_4', :uid => 'uid_4', :role_id => 1})
  User.create({:name => 'James Monroe', :email => 'email_5', :uid => 'uid_5', :role_id => 1})
  User.create({:name => 'John Quincy Adams', :email => 'email_6', :uid => 'uid_6', :role_id => 1})
  User.create({:name => 'Andrew Jackson', :email => 'email_7', :uid => 'uid_7', :role_id => 1})
  User.create({:name => 'Martin Van Buren', :email => 'email_8', :uid => 'uid_8', :role_id => 1})
  User.create({:name => 'William Henry Harrison', :email => 'email_9', :uid => 'uid_9', :role_id => 1})
  User.create({:name => 'John Tyler', :email => 'email_10', :uid => 'uid_10', :role_id => 1})
  User.create({:name => 'James K. Polk', :email => 'email_11', :uid => 'uid_11', :role_id => 1})
  User.create({:name => 'Zachary Taylor', :email => 'email_12', :uid => 'uid_12', :role_id => 1})
  User.create({:name => 'Millard Fillmore', :email => 'email_13', :uid => 'uid_13', :role_id => 1})
  User.create({:name => 'Franklin Pierce', :email => 'email_14', :uid => 'uid_14', :role_id => 1})
  User.create({:name => 'James Buchanan', :email => 'email_15', :uid => 'uid_15', :role_id => 1})
  User.create({:name => 'Abraham Lincoln', :email => 'email_16', :uid => 'uid_16', :role_id => 1})
  User.create({:name => 'Andrew Johnson', :email => 'email_17', :uid => 'uid_17', :role_id => 1})
  User.create({:name => 'Ulysses S. Grant', :email => 'email_18', :uid => 'uid_18', :role_id => 1})
  User.create({:name => 'Rutherford B. Hayes', :email => 'email_19', :uid => 'uid_19', :role_id => 1})
  User.create({:name => 'James A. Garfield', :email => 'email_20', :uid => 'uid_20', :role_id => 1})
  User.create({:name => 'Chester A. Arthur', :email => 'email_21', :uid => 'uid_21', :role_id => 1})
  User.create({:name => 'Grover Cleveland', :email => 'email_22', :uid => 'uid_22', :role_id => 1})
  User.create({:name => 'Benjamin Harrison', :email => 'email_23', :uid => 'uid_23', :role_id => 1})
  User.create({:name => 'Grover Cleveland', :email => 'email_24', :uid => 'uid_24', :role_id => 1})
  User.create({:name => 'William McKinley', :email => 'email_25', :uid => 'uid_25', :role_id => 1})
  User.create({:name => 'Theodore Roosevelt', :email => 'email_26', :uid => 'uid_26', :role_id => 1})
  User.create({:name => 'William Howard Taft', :email => 'email_27', :uid => 'uid_27', :role_id => 1})
  User.create({:name => 'Woodrow Wilson', :email => 'email_28', :uid => 'uid_28', :role_id => 1})
  User.create({:name => 'Warren G. Harding', :email => 'email_29', :uid => 'uid_29', :role_id => 1})
  User.create({:name => 'Calvin Coolidge', :email => 'email_30', :uid => 'uid_30', :role_id => 1})
  User.create({:name => 'Herbert Hoover', :email => 'email_31', :uid => 'uid_31', :role_id => 1})
  User.create({:name => 'Franklin D. Roosevelt', :email => 'email_32', :uid => 'uid_32', :role_id => 1})
  User.create({:name => 'Harry S. Truman', :email => 'email_33', :uid => 'uid_33', :role_id => 1})
  User.create({:name => 'Dwight D. Eisenhower', :email => 'email_34', :uid => 'uid_34', :role_id => 1})
  User.create({:name => 'John F. Kennedy', :email => 'email_35', :uid => 'uid_35', :role_id => 1})
  User.create({:name => 'Lyndon B. Johnson', :email => 'email_36', :uid => 'uid_36', :role_id => 1})
  User.create({:name => 'Richard Nixon', :email => 'email_37', :uid => 'uid_37', :role_id => 1})
  User.create({:name => 'Gerald Ford', :email => 'email_38', :uid => 'uid_38', :role_id => 1})
  User.create({:name => 'Jimmy Carter', :email => 'email_39', :uid => 'uid_39', :role_id => 1})
  User.create({:name => 'Ronald Reagan', :email => 'email_40', :uid => 'uid_40', :role_id => 1})
  User.create({:name => 'George H.W. Bush', :email => 'email_41', :uid => 'uid_41', :role_id => 1})
  User.create({:name => 'Bill Clinton', :email => 'email_42', :uid => 'uid_42', :role_id => 1})
  User.create({:name => 'George W. Bush', :email => 'email_43', :uid => 'uid_43', :role_id => 1})
  User.create({:name => 'Barack Obama', :email => 'email_44', :uid => 'uid_44', :role_id => 1})
end