Badge.create({:id => 1, :name => 'Survivor', :description => 'This badge certifies the player made it through extraction.'})
Badge.create({:id => 2, :name => 'Survivor*', :description => 'Does it really count if you extract with an asterisk next to your name?'})
Badge.create({:id => 3, :name => 'Winning', :description => 'Tagged within the first hour of play.'})
Badge.create({:id => 4, :name => "Murphy's Law", :description => 'Tagged while going to classes on Monday.'})
Badge.create({:id => 5, :name => 'MVP', :description => 'Get tagged twice in a single day.'})
Badge.create({:id => 6, :name => 'Hotshot', :description => '2 tags within an hour of each other.'})
Badge.create({:id => 7, :name => '3 tags'})
Badge.create({:id => 8, :name => '5 tags'})
Badge.create({:id => 9, :name => '10 tags'})
Badge.create({:id => 10, :name => '15 tags'})
Badge.create({:id => 11, :name => 'Unstoppable', :description => '20 tags'})
Badge.create({:id => 12, :name => 'Is it the shoes?', :description => '25 tags.'})
Badge.create({:id => 13, :name => 'Lord of War', :description => '30 tags. Do you even bother to attend class?'})
Badge.create({:id => 14, :name => 'Juggernaut', :description => "5 tags in single day. Even walls can't stop you."})
Badge.create({:id => 15, :name => 'Patient Zero', :description => 'Chosen as original zombie'})
Badge.create({:id => 16, :name => 'Rise and Shine', :description => 'Get a tag between 6AM and 9 AM.'})
Badge.create({:id => 17, :name => 'I found Waldo', :description => 'Submit a geolocation tag.'})
Badge.create({:id => 18, :name => "I've had worse", :description => 'Use an antivirus.'})
Badge.create({:id => 19, :name => 'Better luck next time', :description => 'Tagged after using an AV.'})