source 'https://rubygems.org'

gem 'rails', '4.1.5'
gem 'rails-api', '0.2.0'

gem 'seedbank', '0.3.0'

gem 'devise', '3.2.4'

gem 'active_model_serializers', '0.8.1'

gem 'httparty', '0.13.1'

gem 'carrierwave', '0.10.0'
gem 'mini_magick', '3.8.0'

gem 'wisper', '1.3.0'

gem 'acts_as_votable', '0.10.0'
gem 'counter_culture', '0.1.23'

gem 'rack-cors', :require => 'rack/cors'

group :development do
  gem 'better_errors',     '1.0.1'
  gem 'binding_of_caller', '0.7.2'
  gem 'debugger',          '1.6.8'
end

group :development, :test do
  gem 'sqlite3',  '1.3.9'
  gem 'rspec-rails', '3.0.2'
  gem 'shoulda-matchers', '2.6.2'
  gem 'machinist', '2.0'
end